URL_MAPPING = {
    "Admissions": "https://www.bassetths.org.uk/admissions/",
    "The Admissions Journey": "https://www.bassetths.org.uk/admissions/how-to-join/",
    "Apply for a Place": "https://www.bassetths.org.uk/admissions/apply-for-a-place/",
    "Enquiry & Prospectus": "https://www.bassetths.org.uk/admissions/get-in-touch/",
    "Visit Us": "https://www.bassetths.org.uk/visit-us/",
    "Open Day": "https://www.bassetths.org.uk/admissions/attend-a-stay-and-play/",
    "Attend a Stay & Play": "https://www.bassetths.org.uk/admissions/attend-a-stay-and-play/",
    "Year Of Entry Calculator": "https://www.bassetths.org.uk/admissions/year-of-entry-calculator/",
    "Nursery & Reception entry in September 2025": "https://www.bassetths.org.uk/nursery-reception-book-a-tour/",
    "Events Calendar": "https://www.bassetths.org.uk/school-life/calendar/",
    "Clubs": "https://www.bassetths.org.uk/enrichment/clubs/",
    "Co-Curricular": "https://www.bassetths.org.uk/enrichment/",
    "PE & Games": "https://www.bassetths.org.uk/enrichment/physical-education-sport/",
    "Performing & Creative Arts": "https://www.bassetths.org.uk/enrichment/performing-creative-arts/",
    "Trips": "https://www.bassetths.org.uk/enrichment/trips/",
    "Fees": "https://www.bassetths.org.uk/admissions/fees/",
    "Policies": "https://www.bassetths.org.uk/about/policies/",
    "FAQs": "https://www.bassetths.org.uk/early-years/faqs/",
    "Privacy": "https://www.bassetths.org.uk/privacy-policy/",
    "Cookie Policy": "https://www.bassetths.org.uk/cookie-policy/",
    "School Life": "https://www.bassetths.org.uk/school-life/",
    "Pastoral Care": "https://www.bassetths.org.uk/school-life/pastoral-care/",
    "Uniform": "https://www.bassetths.org.uk/school-life/uniform/",
    "Term Dates": "https://www.bassetths.org.uk/school-life/term-dates/",
    "Nursery School": "https://www.bassetths.org.uk/early-years/nursery-school/",
    "Montessori Approach": "https://www.bassetths.org.uk/early-years/montessori-approach/",
    "A Love of Learning": "https://www.bassetths.org.uk/early-years/inspiring-a-love-of-learning/",
    "About the Nursery School": "https://www.bassetths.org.uk/early-years/nursery-school/",
    "Curriculum": "https://www.bassetths.org.uk/prep-6-11-yrs/curriculum/",
    "Prep \"Ages 4 – 11\"": "https://www.bassetths.org.uk/prep-6-11-yrs/",
    "Teaching Philosophy": "https://www.bassetths.org.uk/prep-6-11-yrs/teaching-philosophy/",
    "Continuous Provision": "https://www.bassetths.org.uk/prep-6-11-yrs/continuous-provision/",
    "Academic Success": "https://www.bassetths.org.uk/about/academic-success/",
    "11+ & Destination Schools": "https://www.bassetths.org.uk/prep-6-11-yrs/senior-school-places/",
    "Scholarships for Senior School places": "https://www.bassetths.org.uk/prep-6-11-yrs/senior-school-places/",
    "Head’s Welcome": "https://www.bassetths.org.uk/about/heads-welcome/",
    "Bassett Life": "https://www.bassetths.org.uk/2025/06/13/bassett-life-3/",
    "News": "https://www.bassetths.org.uk/news/",
    "Read all news": "https://www.bassetths.org.uk/news/",
    "About": "https://www.bassetths.org.uk/about/",
    "Contact": "https://www.bassetths.org.uk/contact/",
    "Work with us": "https://www.bassetths.org.uk/about/work-with-us/",
    "Facilities": "https://www.bassetths.org.uk/about/facilities/",
    "Governance": "https://www.bassetths.org.uk/about/governance/",
    "Dukes Education": "https://www.bassetths.org.uk/about/dukes-education/",
    "Our Aims, Mission & Values": "https://www.bassetths.org.uk/about/our-aims-mission-values/",
    "Reviews & Reports": "https://www.bassetths.org.uk/about/reviews-reports/"
}
